apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnpg-pod-secret-reader
  namespace: db
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["aws-creds"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-0001-secret-reader
  namespace: db
subjects:
- kind: ServiceAccount
  name: cluster-0001
  namespace: db
roleRef:
  kind: Role
  name: cnpg-pod-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-0001-daily
  namespace: db
spec:
  schedule: "0 0 2 * * *"
  cluster:
    name: cluster-0001
  immediate: false
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-0001
  namespace: db
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.19-system-trixie
  backup:
    barmanObjectStore:
      destinationPath: "s3://cloudnative-pg-bakups-010skdkv11/backups"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY

  storage:
    size: 1Gi
    storageClass: longhorn

  monitoring:
    enablePodMonitor: true
