apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnpg-pod-secret-reader
  namespace: db
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["aws-creds"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-0002-secret-reader
  namespace: db
subjects:
- kind: ServiceAccount
  name: cluster-0002
  namespace: db
roleRef:
  kind: Role
  name: cnpg-pod-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-0002-daily
  namespace: db
spec:
  schedule: "0 0 2 * * *"
  cluster:
    name: cluster-0002
  immediate: false
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-0002 
  namespace: db
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.19-system-trixie
  storage:
    size: 1Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://cloudnative-pg-bakups-010skdkv11/backups"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
  bootstrap:
    recovery:
      source: "aws-s3" # name the source, defined under 'externalClusters'
  externalClusters:
    - name: "aws-s3" # the data source
      barmanObjectStore:
        destinationPath: "s3://cloudnative-pg-bakups-010skdkv11/backups"
        serverName: "cluster-0001" # s3 directory, name of the cluster to restore from, will change with each new cluster
        s3Credentials:
          accessKeyId:
            name: aws-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds
            key: ACCESS_SECRET_KEY

